import os
import re
import google.generativeai as genai
from typing import List, Dict, Any
from dotenv import load_dotenv
from .llm_client import GeminiClient

load_dotenv()

class TestGenerator:
    def __init__(self, test_output_dir: str = "tests/generated"):
        self.test_output_dir = test_output_dir
        os.makedirs(self.test_output_dir, exist_ok=True)
        self.client = GeminiClient()

    def _clean_code(self, text: str) -> str:
        """
        Robustly extracts Python code from LLM Markdown response.
        """
        # 1. Try to find content inside ```python ... ``` or ``` ... ```
        pattern = r"```(?:python)?\n(.*?)```"
        match = re.search(pattern, text, re.DOTALL)
        if match:
            return match.group(1).strip()
        
        # 2. If no markdown blocks, return text but strip common non-code headers
        text = text.strip()
        if text.startswith("Here is"):
            # Try to split by first newline import
            parts = text.split("import pytest")
            if len(parts) > 1:
                return "import pytest" + parts[1]
        
        return text

    def generate_test_suite(self, project_name: str, endpoints: List[Dict[str, Any]], base_url: str = "http://localhost:5000") -> str:
        print(f"Generating tests for {project_name}...")

        endpoints_context = ""
        for i, ep in enumerate(endpoints):
            endpoints_context += f"""
            Endpoint {i+1}: {ep.get('method')} {ep.get('path')}
            Payload: {ep.get('payload_schema')}
            """

        prompt = f"""
        Write a pytest script for these API endpoints. 
        Base URL: {base_url}
        Endpoints: {endpoints_context}

        REQUIREMENTS:
        1. Use 'import pytest' and 'import requests'.
        2. Define a fixture 'base_url'.
        3. Write test functions starting with 'test_'.
        4. CRITICAL: When asserting status code, ALWAYS print the response text if it fails.
           Example: assert response.status_code == 200, f"Expected 200 but got {{response.status_code}}. Response: {{response.text}}"
        5. Return ONLY raw python code.
        """

        try:
            print(f"Sending prompt to LLM (length: {len(prompt)} chars)...")
            response_text = self.client.generate_content(prompt)
            print("Received response from LLM.")
            
            generated_code = self._clean_code(response_text)
            print(f"Cleaned code (length: {len(generated_code)} chars).")
            
            # Sanity Check: Ensure it looks like Python
            if "def test_" not in generated_code:
                print("WARNING: Generated code does not contain 'def test_'")
                generated_code += "\n# WARNING: No tests generated by LLM"

            filename = f"test_{project_name}.py"
            # Fix: ensure absolute path or correct relative path
            file_path = os.path.join(os.getcwd(), self.test_output_dir, filename)
            
            # Ensure directory exists
            os.makedirs(os.path.dirname(file_path), exist_ok=True)
            
            with open(file_path, "w") as f:
                f.write(generated_code)
                
            print(f"Test suite saved to: {file_path}")
            return file_path

        except Exception as e:
            print(f"Error generating tests: {e}")
            return ""